# Generated by Django 5.2.10 on 2026-01-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerExperience',
        ),
        migrations.DeleteModel(
            name='Vision',
        ),
    ]
