# Generated by Django 6.0.1 on 2026-01-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successstory',
            options={'verbose_name': 'Success Story', 'verbose_name_plural': 'Success Stories'},
        ),
        migrations.AddField(
            model_name='successstory',
            name='content_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='title_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
