# Generated by Django 5.2.10 on 2026-01-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0002_alter_successstory_options_successstory_content_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='successstory',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='content_ar',
            field=models.TextField(blank=True, null=True, verbose_name='content_ar'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name_ar'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='title_ar',
            field=models.CharField(blank=True, max_length=150, verbose_name='title_ar'),
        ),
    ]
