# Generated by Django 5.2.10 on 2026-01-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0003_logo_alter_successstory_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='titel')),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='titel_ar')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description_ar')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
    ]
