# Generated by Django 6.0.1 on 2026-01-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0003_logo_alter_successstory_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='titel')),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='titel_ar')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description_ar')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logos'},
        ),
        migrations.AlterField(
            model_name='successstory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='success_stories/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
