# Generated by Django 5.2.10 on 2026-01-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0006_alter_service_created_at_alter_service_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhyChooseUs',
            new_name='Advantage',
        ),
    ]
