# Generated by Django 5.2.10 on 2026-01-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0007_rename_whychooseus_advantage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='title_ar')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description_ar')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goals/icons/')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': 'Advantage', 'verbose_name_plural': 'Advantages'},
        ),
    ]
