# Generated by Django 5.2.10 on 2026-01-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0008_goal_alter_advantage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='configurations/', verbose_name='certificate_image')),
                ('certificate_description', models.TextField(blank=True, verbose_name='certificate_description')),
                ('certificate_description_ar', models.TextField(blank=True, null=True, verbose_name='certificate_description_ar')),
                ('Our_message', models.TextField(blank=True, verbose_name='Our_message')),
                ('Our_message_ar', models.TextField(blank=True, null=True, verbose_name='Our_message_ar')),
                ('Our_vision', models.TextField(blank=True, verbose_name='Our_vision')),
                ('Our_vision_ar', models.TextField(blank=True, null=True, verbose_name='Our_vision_ar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.AlterField(
            model_name='advantage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='why_choose_us/icons/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goals/icons/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='image'),
        ),
    ]
