# Generated by Django 5.2.10 on 2026-01-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0009_configuration_alter_advantage_image_alter_goal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='About_the_Center',
            field=models.TextField(blank=True, verbose_name='About_the_Center'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='About_the_Center_ar',
            field=models.TextField(blank=True, null=True, verbose_name='About_the_Center_ar'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='Future_vision',
            field=models.TextField(blank=True, verbose_name='Future vision'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='Future_vision_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Future vision_ar'),
        ),
    ]
