# Generated by Django 5.2.10 on 2026-01-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0009_configuration_alter_advantage_image_alter_goal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='Customer_experience',
            field=models.TextField(blank=True, verbose_name='Customer experience'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='Customer_experience_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Customer experience_ar'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='Social_responsibility',
            field=models.TextField(blank=True, verbose_name='Social responsibility'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='Social_responsibility_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Social responsibility_ar'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='Technical_innovation',
            field=models.TextField(blank=True, verbose_name='Technical_innovation'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='Technical_innovation_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Technical_innovation_ar'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='address_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address_ar'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone_number'),
        ),
    ]
