# Generated by Django 6.0.1 on 2026-01-31 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0010_configuration_about_the_center_and_more'),
        ('configrations', '0010_configuration_customer_experience_and_more'),
    ]

    operations = [
    ]
