# Generated by Django 6.0.1 on 2026-01-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0012_alter_advantage_id_alter_configuration_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_at'),
        ),
    ]
