# Generated by Django 6.0.1 on 2026-02-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0013_configuration_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='advantage',
            name='description_ar',
        ),
        migrations.AlterField(
            model_name='advantage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='why_choose_us/icons/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='certificate_image',
            field=models.FileField(blank=True, null=True, upload_to='configurations/', verbose_name='certificate_image'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='goals/icons/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.FileField(upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='services/icons/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='success_stories/', verbose_name='image'),
        ),
    ]
