# Generated by Django 6.0.1 on 2026-02-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0014_remove_advantage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='description_ar',
        ),
    ]
