# Generated by Django 6.0.1 on 2026-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0015_remove_goal_description_remove_goal_description_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
    ]
