# Generated by Django 6.0.1 on 2026-02-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0016_alter_successstory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='management_message',
            field=models.TextField(blank=True, verbose_name='management_message'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='management_message_ar',
            field=models.TextField(blank=True, null=True, verbose_name='management_message_ar'),
        ),
    ]
