# Generated by Django 6.0.1 on 2026-05-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configrations", "0017_configuration_management_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="whatsapp_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="whatsapp_number"
            ),
        ),
    ]
